// Explicit correspondence to captured DOM records, not visual estimates.
const type=['font-family','font-size','font-weight','line-height','letter-spacing','color'];
const text=(value,tag)=>e=>e.directText===value&&(!tag||e.tag===tag);
const starts=value=>e=>e.directText?.startsWith(value);
const cls=value=>e=>e.class===value;
module.exports={type,mappings:[
 ['home','.logo,.footer-brand',text('sunny patel','a')],
 ['home','.availability',text('Open to software roles')],
 ['home','.intro',starts('I build full-stack software')],
 ['home','.eyebrow',text('selected work')],
 ['home','.all-projects',text('All projects','a')],
 ['home','.path-link',text('See the full path','a')],
 ['home','.project-name',text('ATS Screener','h3')],
 ['home','.project-description',text('The check NVIDIA never shipped','p')],
 ['home','.project-status',text('Actively maintained','span')],
 ['home','.capability-description',starts('Real-time, type-safe web apps')],
 ['home','.capability-number',e=>e.directText==='01'&&e.class==='font-mono text-xs text-ember tabular-nums'],
 ['home','.footer-location',starts('Software developer, Greater Toronto')],
 ['home','.footer-note',text('© 2026 Sunny Patel')],
 ['home','.footer-credit',text('Designed and built from scratch.')],
 ['projects','.detail-copy>h2',text('ATS Screener','h2')],
 ['projects','.detail-subtitle',text('The check NVIDIA never shipped','p')],
 ['projects','.detail-description',starts('On NVIDIA sm_120')],
 ['projects','.tag-list span',text('NVIDIA SASS','li')],
 ['projects','.research-intro',starts('Most students never write')],
 ['projects','.research-copy h2',text('When Semantic Caches Lie','h3')],
 ['projects','.research-subtitle',starts('Independent research, sole author')],
 ['projects','.research-description',starts('Why one similarity threshold')],
 ['projects','.more-subtitle',text('40+ network tools in one app','p')],
 ['projects','.more-description',starts('A cross-platform network engineering')],
 ['work','.experience-detail h2',text('IT Technician','h3')],
 ['work','.experience-summary',starts('Kept the devices, networks')],
 ['work','.experience-detail li',starts('Helped migrate 3,000+')],
 ['work','.education-list li',text("President's List, Winter 2025",'li')],
 ['about','.profile-facts span',text('Currently','dt')],
 ['about','.profile-facts strong',text('Greater Toronto Area','dd')],
 ['about','.bio-copy p',starts("I'm the developer you hand")],
 ['about','.now-block li',starts('Building full-stack AI features')],
 ['about','.tool-tags span',text('TypeScript','li')],
 ['resume','.resume-open',text('Open in new tab','a')],
 ['contact','.contact-intro',starts('Open to new-grad roles and hard problems.')],
 ['contact','.contact-email',text('sunnypatel124555@gmail.com','a')],
 ['contact','.contact-links a',text('github.com/sunnypatell','a')],
 ['contact','.contact-links>span',text('Greater Toronto Area, Canada','li')],
 ['contact','.form-row label',text('Name','label')],
 ]};
