const fs=require('fs'),path=require('path');
const pages=['home','projects','work','about','resume','contact'],widths=[1440,1024,768,390];
const load=n=>JSON.parse(fs.readFileSync(path.join(__dirname,n+'.json'),'utf8'));
const data=pages.flatMap(p=>widths.map(w=>load(p+'-'+w))),home=load('home-1440');
const clean=x=>String(x??'').replace(/\|/g,'&#124;').replace(/\n/g,' ');
const code=x=>'`'+clean(x).replace(/`/g,"'")+'`';
const table=(heads,rows)=>'| '+heads.join(' | ')+' |\n| '+heads.map(()=>'---').join(' | ')+' |\n'+rows.map(r=>'| '+r.map(clean).join(' | ')+' |').join('\n')+'\n\n';
const unique=(a,key=JSON.stringify)=>[...new Map(a.map(x=>[key(x),x])).values()];
const label=e=>(e.directText||e.text||e.class||e.tag).slice(0,72);
let spec='# sunnypatel.net — measured design specification\n\n';
spec+='Captured '+home.capturedAt+' from https://www.sunnypatel.net/. Chromium, CSS viewport widths 1440 / 1024 / 768 / 390, fixed height 900 CSS px, devicePixelRatio 1. Width tests are responsive desktop-browser tests, not touch-device emulation. Default dark appearance, no reduced-motion override. Each page was scrolled to trigger lazy assets/reveals, then returned to the top. Values are literal computed CSS strings unless marked source. Fractional pixel values are retained. Hidden DOM elements are included and marked by their computed display/visibility; do not treat them as visible layout. Some computed colors use oklab(), lab(), or color(srgb); they are preserved rather than approximately converted to hex.\n\n';
spec+='## Evidence and navigation\n\n[Component measurements](COMPONENTS.md) contains per-page, per-width typography, spacing, borders, effects, and transitions. [Assets and icons](ASSETS.md) contains font declarations, loaded font URLs, image sizes, canvas dimensions, and inline SVG markup. [Source CSS](SOURCE-CSS.md) contains root blocks with cascade context, media queries, hover rules, and keyframes. The 24 `page-width.json` files contain all collected DOM records with selectors and full styles. Screenshots are `page-1440.png` and `page-390.png`. [Hover samples](hover-states.json), [mobile menu open](mobile-menu-open.json), and [scrolled header](header-scrolled.json) record additional states.\n\n';
spec+='## Global palette\n\n'+table(['Token (source)','Literal source value'],Object.entries(home.rootVariables).filter(([k])=>k.startsWith('--color-')).map(([k,v])=>[code(k),code(v)]));
spec+='Body computed background: '+code(home.body['background-color'])+'; body text: '+code(home.body.color)+'. Transparent backgrounds and alpha variants are mapped to individual components in COMPONENTS.md. Border base token is `--color-line: #262b30`; alpha borders are distinct values, not the base hex.\n\n';
spec+='## Fonts and shared layout\n\n';
spec+=table(['Role','Computed font stack'],[['Display',home.elements.find(e=>e.tag==='h1').styles['font-family']],['Body',home.body['font-family']],['Monospace UI',home.elements.find(e=>e.class.includes('font-mono')).styles['font-family']]].map(r=>[r[0],code(r[1])]));
spec+='Source Container: `mx-auto w-full max-w-6xl px-6 sm:px-10`: max-width `72rem` = `1152px`; padding-inline `24px` below 640px and `40px` at/above 640px. This is border-box sizing, so usable content at 1440px is `1072px`, not 1152px.\n\n';
spec+='Exact stylesheet width breakpoints: `@media (min-width: 40rem)` = 640px; `48rem` = 768px; `64rem` = 1024px. Three.js additionally evaluates `(max-width: 1024px)` for model scale. No width breakpoint is inferred from screenshots. Source media rules and their declarations are in SOURCE-CSS.md.\n\n';
spec+=table(['Page / H1','1440px size / line-height / spacing','1024px','768px','390px'],pages.map(p=>[p,...widths.map(w=>{let e=load(p+'-'+w).elements.find(e=>e.tag==='h1');return e?code([e.styles['font-size'],e.styles['line-height'],e.styles['letter-spacing']].join(' / ')):'not found'})]));
spec+='## Page components and responsive reflow\n\n';
for(const p of pages){spec+='### '+(p==='home'?'/':'/'+p)+'\n\n';const d=load(p+'-1440');spec+=table(['Component / source classes','1440','1024','768','390'],d.elements.filter(e=>['section','main','header','footer'].includes(e.tag)||e.styles.display==='grid').filter(e=>!e.class.includes('reveal-line')).map(e=>[code(e.tag+' '+e.class),...widths.map(w=>{const other=load(p+'-'+w).elements;const a=other.find(x=>x.selector===e.selector&&x.class===e.class)||other.find(x=>x.class===e.class&&x.tag===e.tag);if(!a)return 'different DOM; see component capture';return code('display='+a.styles.display+'; columns='+a.styles['grid-template-columns']+'; gap='+a.styles.gap+'; padding='+a.styles.padding+'; order='+a.styles.order)})]));}
spec+='## Animation and interaction specifications\n\n';
spec+=table(['Component / trigger','Exact behavior','Evidence'],[
['Section Reveal / enters viewport','opacity 0 → 1; y 18 → 0 (default); duration 0.7s; ease [0.16,1,0.3,1]; delay prop default 0; once true; viewport margin -12% 0px','0wh--ean-efla.js, exported Reveal; Motion/Framer Motion runtime'],
['Text line reveal / ScrollTrigger','GSAP SplitText; yPercent 110 → original; opacity 0 → original; duration 0.9s; ease power3.out; stagger 0.08s default; start top 85%; once true; waits for fonts','32wy4538hz7au.js and route bundles, exported RevealText'],
['Smooth scroll / wheel and anchor','Lenis 1.3.26; ReactLenis root; explicit autoRaf:false, lerp:0.1, anchors:true; driven by GSAP ticker with seconds × 1000; lagSmoothing(0); scroll event updates ScrollTrigger','3a5r6ln92fbj5.js; runtime lenisVersion and html class'],
['Route change','Lenis scrollTo(0,{immediate:true}) plus window.scrollTo(0,0)','3a5r6ln92fbj5.js'],
['Mobile menu / toggle click','grid-template-rows 0fr ↔ 1fr; opacity 0 ↔ 1; 0.3s cubic-bezier(0.22,1,0.36,1); backdrop blur 12px; 1px top border when open','source CSS and mobile-menu-open.json'],
['Hamburger / toggle click','outer lines transition all 0.3s with premium cubic-bezier; rotate ±45deg; middle opacity transition 0.2s','3a5r6ln92fbj5.js'],
['Magnetic control / pointer move and leave','x/y quickTo duration 0.6s, elastic.out(1,0.4); pointer leave returns x/y to 0; fine pointer only; skipped for reduced motion','1rqugfi3q7sw4.js'],
['Custom pointer / pointer move and hover','dot x/y duration 0.12s power3; ring x/y 0.4s power3; interactive hover ring scale 1.8 vs 1 and opacity 1 vs 0.55, duration 0.3s power3.out','3a5r6ln92fbj5.js'],
['Terminal typing / repeated cycle','increments displayed character count every 34ms; holds completed text 2800ms, then restarts; reduced motion shows all characters','32wy4538hz7au.js'],
['Live user count / enters viewport','IntersectionObserver threshold 0.35, disconnects after entry; duration 2500ms; progress easing 1 - 2^(-12*t), endpoint 1','32wy4538hz7au.js / LiveUserCount'],
['3D hero / animation frames','rotation.y = 4.4 + 0.1*sin(0.6*t); rotation.x = -0.03 + 0.025*sin(0.46*t), t = elapsed seconds; active render gated by visibility','3z0rwqtep0jp1.js; 32wy4538hz7au.js observer rootMargin 200px 0px'],
['CSS animation / class-driven','Exact keyframes, durations, and selectors appear in SOURCE-CSS.md and per-element animation columns','Extracted CSSOM; declared rules may not all be used on these routes']]);
spec+='Lenis `window.lenis` exposes version metadata, not the controller instance: its options were verified in the React provider bundle. The html `lenis` class and runtime version were observed. Source includes Motion and GSAP, so attributing every reveal to only one library would be incorrect. CSS transitions use their recorded hover/focus/active selectors as triggers; numeric per-element values are in COMPONENTS.md. Instance-specific Reveal delays must be read from the route bundle; the table above labels defaults explicitly.\n\n';
spec+='## Technical fingerprint\n\nNext.js runtime `window.next.version = '+code(home.runtime.next?.version)+'`; App Router Flight `window.__next_f` is present and `__NEXT_DATA__` is absent. Bundles include Turbopack filenames. Tailwind utility classes, `@layer theme/base/utilities`, `--tw-*` variables, arbitrary-value utilities, and a small global CSS layer are directly observable. Exact Tailwind package version is not exposed. Next font assets are self-hosted WOFF2 variable fonts. Hero uses Three.js, React Three Fiber, GLTF loading and postprocessing; camera and asset details are in ASSETS.md.\n\n';
spec+='Observed analytics: same-origin `/413d7444c1f56fd2/script.js`, Vercel Analytics code. Treat analytics as informational only. Resource inventories include route prefetches; a fetched chunk does not prove its UI was rendered. Contact bundle includes conditional reCAPTCHA support; loading that external script is not assumed without a resource entry.\n\n';
spec+='## Limits and interpretation\n\nThis is an audit of the six requested routes and their captured default states, plus mobile navigation, header scroll state, and representative home hover states. It does not assert exhaustive testing of every possible form error, command-palette result, network fallback, or pointer path. The full CSS hover rules are included even when not individually hovered. Screenshots and canvas bounds do not imply fixed pixel dimensions for a 3D model. Model accessor bounds are in model units, not screen pixels. Loaded font resources are separated from all declared unicode subsets. Responsive measurements at 390px retain the desktop pointer capabilities; any-pointer:coarse behavior is sourced from JS and labeled accordingly. All browser-normalized color strings remain literal, including modern color syntax. No claim of exact RGB equivalence is made for converted color spaces.\n\n';
fs.writeFileSync(__dirname+'/SPEC-SHEET.md',spec);
let components='# Component measurements\n\nEach subsection is one actual page/viewport capture. Selector references resolve in that snapshot. Typography groups combine identical computed text styles within the same section; representative text and a selector are shown. Full membership and every element remain in the JSON capture. Layout rows include every nontrivial grid/flex container, spacing, border, radius, and semantic section. All computed values are literal.\n\n';
for(const d of data){const name=pages.find(p=>d.url.endsWith(p)||p==='home'&&new URL(d.url).pathname==='/');components+='## '+d.url+' — '+d.viewport.width+'px\n\n';
const groups=unique(d.elements.map(e=>e.component));for(const group of groups){const els=d.elements.filter(e=>e.component===group);if(!els.length)continue;components+='### '+code(group)+'\n\n';
 const text=unique(els.filter(e=>e.directText||/^h[1-6]$/.test(e.tag)||['p','button','a','label','input','textarea','kbd'].includes(e.tag)),e=>JSON.stringify(['font-family','font-size','font-weight','line-height','letter-spacing','color','text-transform'].map(k=>e.styles[k])));
 if(text.length)components+=table(['Text / selector','Family','Size','Weight','Line-height','Letter-spacing','Color','Display'],text.map(e=>[label(e)+'<br>'+code(e.selector),code(e.styles['font-family']),e.styles['font-size'],e.styles['font-weight'],e.styles['line-height'],e.styles['letter-spacing'],code(e.styles.color),e.styles.display]));
 const layout=els.filter(e=>['section','main','header','footer','nav','article','button','input','textarea','img'].includes(e.tag)||['grid','flex','inline-flex'].includes(e.styles.display)||e.styles.padding!=='0px'||e.styles.margin!=='0px'||e.styles['border-radius']!=='0px'||['top','right','bottom','left'].some(k=>e.styles['border-'+k+'-width']!=='0px'));
 if(layout.length)components+=table(['Element / selector / class','Box; width limits','Padding; margin','Display / columns / direction / gap / order','Border T R B L; colors; radius','Background'],layout.map(e=>[label(e)+'<br>'+code(e.selector)+'<br>'+code(e.class),code(e.styles.width+' × '+e.styles.height+'; min '+e.styles['min-width']+'; max '+e.styles['max-width']),code(e.styles.padding+'; '+e.styles.margin),code([e.styles.display,e.styles['grid-template-columns'],e.styles['flex-direction'],e.styles.gap,e.styles.order].join('; ')),code(['top','right','bottom','left'].map(k=>e.styles['border-'+k+'-width']).join(' ')+'; '+unique(['top','right','bottom','left'].map(k=>e.styles['border-'+k+'-color'])).join(' / ')+'; '+e.styles['border-radius']),code(e.styles['background-color'])]));
 const effects=els.filter(e=>e.styles['background-image']!=='none'||e.styles.filter!=='none'||e.styles['backdrop-filter']!=='none'||e.styles['box-shadow']!=='none'||e.styles['animation-name']!=='none'||e.styles['transition-duration']!=='0s'||Object.keys(e.pseudo).length);
 if(effects.length)components+=table(['Element','Image / filter / backdrop / shadow / opacity','Transition property; duration; easing; delay','Animation name; duration; easing; delay; iterations'],effects.map(e=>[code(e.selector),code([e.styles['background-image'],e.styles.filter,e.styles['backdrop-filter'],e.styles['box-shadow'],e.styles.opacity].join('; ')),code(['transition-property','transition-duration','transition-timing-function','transition-delay'].map(k=>e.styles[k]).join('; ')),code(['animation-name','animation-duration','animation-timing-function','animation-delay','animation-iteration-count'].map(k=>e.styles[k]).join('; '))]));
 for(const e of effects)for(const [pseudo,s]of Object.entries(e.pseudo))components+='Pseudo '+code(e.selector+pseudo)+':\n\n```json\n'+JSON.stringify(s,null,2)+'\n```\n\n';
}}
fs.writeFileSync(__dirname+'/COMPONENTS.md',components);
let css='# Literal CSSOM rules\n\nBrowser-serialized rules; original downloaded stylesheet is in sources/2umqilmtll602.css. Context distinguishes theme, supports, and print overrides.\n\n';
for(const [title,predicate]of [['Root variable blocks',r=>r.selector?.includes(':root')],['Font variables',r=>r.text.includes('--font-display-src:')||r.text.includes('--font-body-src:')||r.text.includes('--font-mono-src:')],['Media queries',r=>r.type==='CSSMediaRule'],['Hover / focus / active states',r=>r.selector&&/:hover|:focus|:active/.test(r.selector)],['Keyframes and named effects',r=>r.type==='CSSKeyframesRule'||r.selector&&/grain|glow|float-bob|page-enter|cursor|shadow/.test(r.selector)]]){css+='## '+title+'\n\n';for(const r of unique(data.flatMap(d=>d.css).filter(predicate),r=>r.text+JSON.stringify(r.context)))css+='Source: '+r.sheet+'; context: '+code(r.context.join(' > ')||'top-level')+'\n\n```css\n'+r.text+'\n```\n\n';}
css+='## Computed root custom properties (1440px homepage)\n\n```json\n'+JSON.stringify(home.rootVariables,null,2)+'\n```\n';fs.writeFileSync(__dirname+'/SOURCE-CSS.md',css);
let assets='# Fonts, images, icons, 3D and scripts\n\n## Font files\n\nDeclared font faces (variable ranges and unicode-range are literal CSS; declarations are not proof of a network load):\n\n';
for(const r of unique(data.flatMap(d=>d.css).filter(r=>r.type==='CSSFontFaceRule'),r=>r.text))assets+='```css\n'+r.text+'\n```\n\n';
assets+='Observed loaded font URLs:\n\n'+unique(data.flatMap(d=>d.resources).map(r=>r.url).filter(u=>u&&u.includes('.woff'))).map(u=>'- '+u).join('\n')+'\n\n';
assets+='## Images\n\nNatural dimensions are browser image dimensions of the selected resource; srcset density and Next image optimization can differ from original file dimensions. CurrentSrc identifies the exact measured resource.\n\n';
assets+=table(['Page / viewport','Asset / alt','Natural size','Rendered size','Current resource'],data.flatMap(d=>d.images.map(i=>[new URL(d.url).pathname+' / '+d.viewport.width,i.alt,`${i.naturalWidth} × ${i.naturalHeight}`,`${i.width} × ${i.height}`,i.currentSrc])));
assets+='## Inline SVG icons\n\n'+table(['Page / viewport','Selector / class','Rendered size','ViewBox','Computed stroke / width'],data.flatMap(d=>d.svg.map(i=>[new URL(d.url).pathname+' / '+d.viewport.width,code(i.selector)+' '+code(i.class),i.width+' × '+i.height,i.viewBox,code(i.stroke)+' / '+i.strokeWidth])));
for(const s of unique(data.flatMap(d=>d.svg),s=>s.html))assets+='```html\n'+s.html+'\n```\n\n';
assets+='## Hero 3D\n\nSource asset `/models/retro_computer.glb?v=5`, binary glTF (GLB), '+fs.statSync(__dirname+'/sources/retro_computer.glb').size+' bytes. A 3D model has no fixed bitmap width/height. Rendered canvas and backing buffer measurements:\n\n';
assets+=table(['Page / viewport','CSS size','Drawing buffer'],data.flatMap(d=>d.canvas.map(c=>[new URL(d.url).pathname+' / '+d.viewport.width,c.styles.width+' × '+c.styles.height,c.width+' × '+c.height])));
const b=fs.readFileSync(__dirname+'/sources/retro_computer.glb'),g=JSON.parse(b.subarray(20,20+b.readUInt32LE(12)).toString());const glb={asset:g.asset,scenes:g.scenes,nodes:g.nodes,meshes:g.meshes?.map(m=>({name:m.name,primitives:m.primitives.map(p=>({positionAccessor:p.attributes.POSITION,bounds:g.accessors[p.attributes.POSITION]}))})),images:g.images};fs.writeFileSync(__dirname+'/model-metadata.json',JSON.stringify(glb,null,2));
assets+='[Model metadata](model-metadata.json) contains node transforms and POSITION accessor bounds in model units. Source renderer: dpr `[1,1.6]`; camera position `[0,2.59,9.67]`, fov `28`; scale `1.5` at max-width 1024px, otherwise `1.3`; alpha true; antialias true. Ambient intensity `0.55`; spot `[-6,7,7]`, angle `0.5`, penumbra `1`, intensity `130`, color `#ffe9d2`; points `[7,1,4]` intensity `45` color `#d9663d` and `[0,1,7]` intensity `22` color `#ffb27a`. Desktop controls disable zoom/pan; polar angles π/2.4 to π/2.05. Coarse-pointer devices omit OrbitControls. Postprocess brightness `-0.01`, contrast `0.06`, bloom intensity `0.7`, threshold `0.6`, smoothing `0.25`, vignette offset `0.3`, darkness `0.8`.\n\n';
assets+='## Observed scripts\n\n'+unique(data.flatMap(d=>d.scripts).filter(s=>s.src),s=>s.src).map(s=>'- '+s.src).join('\n')+'\n';fs.writeFileSync(__dirname+'/ASSETS.md',assets);
console.log('Generated SPEC-SHEET.md, COMPONENTS.md, SOURCE-CSS.md, ASSETS.md and model-metadata.json.');
